language: python
branches:
  only:
  - master
install:
- pip install requests
- pip install -r requirements.txt
before_script:
- pelican-themes -i ./theme/elegant
script:
- make publish
- make ssh_upload
before_install:
- touch ~/.ssh/id_rsa
- openssl aes-256-cbc -K $encrypted_0579895ad733_key -iv $encrypted_0579895ad733_iv -in id_rsa.enc -out ~\/.ssh/id_rsa -d
addons:
  ssh_known_hosts: 128.199.103.86
