language: python
branches:
  only:
  - master
addons:
  ssh_known_hosts: 128.199.103.86
before_install:
- openssl aes-256-cbc -K $encrypted_0579895ad733_key -iv $encrypted_0579895ad733_iv -in id_rsa.enc -out /tmp/id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/id_rsa
- ssh-add /tmp/id_rsa
install:
- pip install requests
- pip install -r requirements.txt
before_script:
- pelican-themes -i ./theme/elegant
script:
- make publish
- make ssh_upload
